### ISSUE TITLE
ＣＩＮ计算问题

### ISSUE THREAD

**Issue by Deermini** [batch-norm/RI-DeepFM#4]
你好，想请教你一个问题．那个将ｃｏｎｆｉｇ.py中的CIN_layer = True 时，程序２４４行报错，我分析了下觉得那个ｓｅｌｆ.field_size应该改为ｓｅｌｆ.single_size,改完后可以运行过去，但是运行到cross_layer_size的最后一层时２５２行报错维度不匹配，检查了很久还是不太明白哪里，不知道大神能否帮忙解答一下，谢谢啦．

**Comment by TzeSing** [comment]
同问，为什么Config里面的CIN_layer = True之后会报这个错误

`Traceback (most recent call last):
  File "C:\Users\Administrator\Desktop\xDeepFM-master\venv\lib\site-packages\tensorflow\python\client\session.py", line 1356, in _do_call
    return fn(*args)
  File "C:\Users\Administrator\Desktop\xDeepFM-master\venv\lib\site-packages\tensorflow\python\client\session.py", line 1341, in _run_fn
    options, feed_dict, fetch_list, target_list, run_metadata)
  File "C:\Users\Administrator\Desktop\xDeepFM-master\venv\lib\site-packages\tensorflow\python\client\session.py", line 1429, in _call_tf_sessionrun
    run_metadata)
tensorflow.python.framework.errors_impl.InvalidArgumentError: Input to reshape is a tensor with 131072 values, but the requested shape requires a multiple of 176
	 [[{{node Reshape_5}}]]

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:/Users/Administrator/Desktop/xDeepFM-master/xDeepFM.py", line 361, in <module>
    xdeep = xDeepFM()
  File "C:/Users/Administrator/Desktop/xDeepFM-master/xDeepFM.py", line 37, in __init__
    self._train()
  File "C:/Users/Administrator/Desktop/xDeepFM-master/xDeepFM.py", line 339, in _train
    feed_dict=batch_dict)
  File "C:\Users\Administrator\Desktop\xDeepFM-master\venv\lib\site-packages\tensorflow\python\client\session.py", line 950, in run
    run_metadata_ptr)
  File "C:\Users\Administrator\Desktop\xDeepFM-master\venv\lib\site-packages\tensorflow\python\client\session.py", line 1173, in _run
    feed_dict_tensor, options, run_metadata)
  File "C:\Users\Administrator\Desktop\xDeepFM-master\venv\lib\site-packages\tensorflow\python\client\session.py", line 1350, in _do_run
    run_metadata)
  File "C:\Users\Administrator\Desktop\xDeepFM-master\venv\lib\site-packages\tensorflow\python\client\session.py", line 1370, in _do_call
    raise type(e)(node_def, op, message)
tensorflow.python.framework.errors_impl.InvalidArgumentError: Input to reshape is a tensor with 131072 values, but the requested shape requires a multiple of 176
	 [[node Reshape_5 (defined at /Users/Administrator/Desktop/xDeepFM-master/xDeepFM.py:242) ]]

Errors may have originated from an input operation.
Input Source operations connected to node Reshape_5:
 Reshape_2 (defined at /Users/Administrator/Desktop/xDeepFM-master/xDeepFM.py:185)

Original stack trace for 'Reshape_5':
  File "/Users/Administrator/Desktop/xDeepFM-master/xDeepFM.py", line 361, in <module>
    xdeep = xDeepFM()
  File "/Users/Administrator/Desktop/xDeepFM-master/xDeepFM.py", line 18, in __init__
    self._init_Model()
  File "/Users/Administrator/Desktop/xDeepFM-master/xDeepFM.py", line 242, in _init_Model
    shape=[-1, self.field_size, Config.embedding_size])
  File "\Users\Administrator\Desktop\xDeepFM-master\venv\lib\site-packages\tensorflow\python\ops\gen_array_ops.py", line 9093, in reshape
    "Reshape", tensor=tensor, shape=shape, name=name)
  File "\Users\Administrator\Desktop\xDeepFM-master\venv\lib\site-packages\tensorflow\python\framework\op_def_library.py", line 788, in _apply_op_helper
    op_def=op_def)
  File "\Users\Administrator\Desktop\xDeepFM-master\venv\lib\site-packages\tensorflow\python\util\deprecation.py", line 507, in new_func
    return func(*args, **kwargs)
  File "\Users\Administrator\Desktop\xDeepFM-master\venv\lib\site-packages\tensorflow\python\framework\ops.py", line 3616, in create_op
    op_def=op_def)
  File "\Users\Administrator\Desktop\xDeepFM-master\venv\lib\site-packages\tensorflow\python\framework\ops.py", line 2005, in __init__
    self._traceback = tf_stack.extract_stack()`

**Comment by ccfccl** [comment]
同问

**Comment by zkailinzhang** [comment]
if set  CIN_layer = True, 
modify line240 - line245:

```
if Config.multi_features:
    nn_input = tf.reshape(tf.concat([second_single_result, second_numerical_result,second_multi_result], axis=1),
                            shape=[-1, self.field_size, Config.embedding_size])
else:
    nn_input = tf.reshape(tf.concat([second_single_result,second_numerical_result], axis=1),
                            shape=[-1, self.field_size, Config.embedding_size])
```

**Comment by ucasiggcas** [comment]
hi,dear大佬
请教下数据中的header是啥意思啊？指点下啊，多谢

  | user_id | label | all_launch_count | last_launch | all_video_count | last_video | all_video_day | all_action_count | last_action | all_action_day | register_type | device_type | register_day | multi
